baseURL = "https://jolynch.github.io/"
languageCode = "en-us"
title = "Joey Lynch's Site"
theme = "xmin"

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/posts/"

[params]
    description = "A personal website for Joey Lynch built with Hugo."
    footer = "&copy; [Joey Lynch](https://jolynch.github.io) 2019 | [Github](https://github.com/jolynch)"
