baseURL = "https://jolynch.github.io/"
googleAnalytics = "UA-155022966-1"
languageCode = "en-us"
title = "Joey Lynch's Site"
theme = "xmin"

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 2
    url = "/posts/"
[[menu.main]]
    name = "Tags"
    weight = 3
    url = "/tags/"
[[menu.main]]
    name = "RSS"
    url = "/index.xml"

[params]
    description = "A personal website for Joey Lynch."
    footer = "&copy; [Joey Lynch](https://jolynch.github.io) 2019 | [Github](https://github.com/jolynch)"
    mainSections = ["posts"]

[markup.goldmark.renderer]
unsafe= true
